"""empty message

Revision ID: a70bdd39c6d3
Revises: 2af19c4b83d0
Create Date: 2017-08-14 10:20:37.336982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70bdd39c6d3'
down_revision = '2af19c4b83d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'locations', ['location'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'location')
    # ### end Alembic commands ###
